### ISSUE TITLE
Feature Request: Play selected text on keyboard shortcut

### ISSUE THREAD

**Issue by jonleung** [hmirin/speechy#4]
Hi @hmirin, thanks so much for creating this extension! I have a feature request to play a selected piece of text upon executing a keyboard shortcut!

Thanks so much!
Jonathan

**Comment by hmirin** [comment]
Thanks @jonleung for your request! It seems to be very useful. I'll add this feature in the future release.

**Comment by jonleung** [comment]
❤️️

**Comment by hmirin** [comment]
Update: Current implementation may contain a bug. 
- Speechy won't get the selected text sometimes.
  - It seems to be related to Chrome's permission.
I'll look into this issue. Please wait some more!
